<a href="https://colab.research.google.com/github/danielrobl3s/ML-notebooks/blob/main/New_York_Average_Temperature_SVR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Average temperature of New York city using linear regression, multiple linear regression, polynomial regression and support vector regression

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import mean_squared_error

#Importing the dataset

In [3]:
dataset = pd.read_csv('nyc_temperature.csv')

In [4]:
#Replace 'T' (the missing values), to be null to be taken care of later
dataset.replace('T', 'NaN', inplace=True)

X = dataset.loc[:,:]
X = dataset.drop(columns=['date', 'tavg'])
X = X.values
Y = dataset.loc[:,'tavg'].values

In [5]:
print(X)

[[60 40 13.9 ... '0.08' '0' '0']
 [41 35 2.1 ... '0' '0' '0']
 [45 39 6.3 ... 'NaN' '0' '0']
 ...
 [44 38 4.3 ... '0.29' '0' '0']
 [43 38 4.0 ... '0.49' '0' '0']
 [46 38 5.7 ... '0.01' '0' '0']]


In [6]:
print(Y)

[50.  38.  42.  42.  44.5 40.5 30.5 41.  40.5 32.5 27.  27.5 29.  28.5
 31.  35.5 30.  35.5 35.5 28.  10.5 22.5 38.5 46.  34.5 30.  39.  32.
 34.5 21.5 10.  17.  26.5 41.5 47.5 50.5 40.5 40.5 44.  28.5 30.  34.
 30.5 37.5 39.5 48.5 39.  31.5 34.  30.  29.  42.  40.  35.5 41.  35.5
 31.  26.  31.  30.5 35.5 37.5 33.5 26.5 23.  26.  31.  40.5 39.  46.
 38.5 39.  49.  60.  48.  39.5 39.5 42.5 44.  42.5 43.5 41.5 49.  50.
 40.5 39.  44.  53.  55.5 49.5 39.5 43.5 54.  51.5 42.  52.5 55.  63.
 46.5 51.  46.  55.5 66.5 63.  53.5 54.  54.  56.5 65.5 58.5 57.5 54.5
 64.5 61.  56.  55.5 52.5 49.  51.5 52.5 51.5 59.  50.  59.  51.5 58.
 58.  61.  56.5 64.5 63.5 51.5 46.  48.  58.  64.  70.5 67.  68.  77.
 64.  66.5 66.5 68.5 63.5 75.5 73.5 66.5 62.  62.  71.  71.5 73.  66.
 65.  74.  77.  72.  71.5 69.5 64.5 70.5 68.  61.  68.5 73.  75.5 73.
 70.  68.  70.  71.5 71.5 76.5 78.  79.  79.5 81.  82.  85.  78.  77.5
 81.5 81.  82.  78.5 84.5 79.  75.5 80.  82.5 80.  81.5 80.5 85.  80.5
 83.5 84.  74.5

#Taking care of missing data

In [27]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,5:])
X[:,5:] = imputer.transform(X[:,5:])

In [28]:
print(X)

[[60 40 13.9 ... 0.08 0.0 0.0]
 [41 35 2.1 ... 0.0 0.0 0.0]
 [45 39 6.3 ... 0.16249201277955272 0.0 0.0]
 ...
 [44 38 4.3 ... 0.29 0.0 0.0]
 [43 38 4.0 ... 0.49 0.0 0.0]
 [46 38 5.7 ... 0.01 0.0 0.0]]


In [29]:
Y = Y.reshape(len(Y), 1)
print(Y)

[[50. ]
 [38. ]
 [42. ]
 [42. ]
 [44.5]
 [40.5]
 [30.5]
 [41. ]
 [40.5]
 [32.5]
 [27. ]
 [27.5]
 [29. ]
 [28.5]
 [31. ]
 [35.5]
 [30. ]
 [35.5]
 [35.5]
 [28. ]
 [10.5]
 [22.5]
 [38.5]
 [46. ]
 [34.5]
 [30. ]
 [39. ]
 [32. ]
 [34.5]
 [21.5]
 [10. ]
 [17. ]
 [26.5]
 [41.5]
 [47.5]
 [50.5]
 [40.5]
 [40.5]
 [44. ]
 [28.5]
 [30. ]
 [34. ]
 [30.5]
 [37.5]
 [39.5]
 [48.5]
 [39. ]
 [31.5]
 [34. ]
 [30. ]
 [29. ]
 [42. ]
 [40. ]
 [35.5]
 [41. ]
 [35.5]
 [31. ]
 [26. ]
 [31. ]
 [30.5]
 [35.5]
 [37.5]
 [33.5]
 [26.5]
 [23. ]
 [26. ]
 [31. ]
 [40.5]
 [39. ]
 [46. ]
 [38.5]
 [39. ]
 [49. ]
 [60. ]
 [48. ]
 [39.5]
 [39.5]
 [42.5]
 [44. ]
 [42.5]
 [43.5]
 [41.5]
 [49. ]
 [50. ]
 [40.5]
 [39. ]
 [44. ]
 [53. ]
 [55.5]
 [49.5]
 [39.5]
 [43.5]
 [54. ]
 [51.5]
 [42. ]
 [52.5]
 [55. ]
 [63. ]
 [46.5]
 [51. ]
 [46. ]
 [55.5]
 [66.5]
 [63. ]
 [53.5]
 [54. ]
 [54. ]
 [56.5]
 [65.5]
 [58.5]
 [57.5]
 [54.5]
 [64.5]
 [61. ]
 [56. ]
 [55.5]
 [52.5]
 [49. ]
 [51.5]
 [52.5]
 [51.5]
 [59. ]
 [50. ]
 [59. ]
 [51.5]


#Feature scaling

In [30]:
from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()
sc_Y = StandardScaler()

X = sc_X.fit_transform(X)
Y = sc_Y.fit_transform(Y)

#Train the SVR model

In [31]:
from sklearn.svm import SVR
regressor = SVR(kernel='rbf')
regressor.fit(X, Y)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

#Predict new result

In [33]:
sc_Y.inverse_transform(regressor.predict(sc_X.transform([[60, 40, 13.9, 15, 0, 0.08, 0, 0]])).reshape(-1, 1))

array([[51.49562526]])